### ISSUE TITLE
Geocoding Issues

### ISSUE THREAD

**Issue by cblevins** [regan008/MGG-LC-Data#27]
There seem to be a few categories of places that aren’t getting geocoded: 

- [x] Places that are returning a geocoding API warning because there are multiple results, but then our code is defaulting to NA: ex. `Dover, NJ, United States`, `Laguna, CA, United States` - I think we just want to change our code to take the first or default value. 
- [ ] Places that have been transcribed incorrectly in either the city or state fields: ex. `Salt Lake City, TX, United States`, `Fargo, NC, United States`, etc. I think we need to go back and fix typos, the question is where - Airtable would be the cleanest in terms of ensuring it's fixed as close to teh root as possible, but would be more laborious. If we want to edit a CSV file directly in our repository we just need to make sure that we're not overwriting it with our R script.
- [ ] Places that the geocoding service really can't locate. This would probably mean trying to geocode them by hand and using a separate CSV file in the `geocoding-files` folder that doesn't get modified at all by our R script and instead is used as a lookup table. So basically, try to geocode, then try and see if any values in `failed-geocode.csv` match in the lookup table. I'm still not sure exactly the right steps for this...

**Comment by regan008** [comment]
Ok, I've been digging into this bug this morning. I got the first item handled.

But we have a bug somewhere, and I'm trying to track down where it's being introduced. For example, Deer Park, NY, has been geocoded and shows up in unique-locations-geocoded.csv. But once prep_geocode() is run, it's being added to the list of unique locations to geocode, and I can't figure out why that is.

**Comment by regan008** [comment]
@cblevins Ok I figured out the issue here! In the geocoding function it was giving anything that returned a warning an NA value. Warnings occur on many entries where there could be more than one entry (like Lake Tahoe which is both a city and geographical feature.) I edited the script so that it only adds NA values for true errors and a spot check shows that everything was geocoded correctly. It even gets entries where there is a slight error like "Tijuana, CA". 

For future debugging, I also added a script called `geocoding-error-identifier.R` that will pull any NA values and tell us which year, publication, and location the NA values are referencing. 

I mentioned the wrong issue number in the commit but its `0c7da0c`
